apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-service
spec:
  selector:
    matchLabels:
      name: daemon-label
  template:
    metadata:
      labels:
        name: daemon-label
    spec:
      containers:
        - name: daemon-container
          image: busybox
          args:
          - /bin/sh
          - -c
          - >
            while true;
            do
              echo "Running as a Daemon service";
              sleep 1;
            done;