apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  template:
    spec:
      containers:
      - name: batch-container
        image: busybox
        args:
        - /bin/sh
        - -c
        - echo "Executed at $(date)"
      restartPolicy: Never