apiVersion: v1
kind: Pod
metadata:
  name: resource-limit-pod
spec:
  containers:
  - name: limit-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - >
      while true;
      do
        echo "Running forever";
        sleep 1;
      done;
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi